import { AuthProvider } from '@/app/contexts/AuthContext';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import LayoutWrapper from './components/layouts/LayoutWrapper';
import PrimaryLayout from './components/layouts/primary/PrimaryLayout';
import './globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Lumea',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans`}
      >
        <AuthProvider>
          <PrimaryLayout>
            <LayoutWrapper>
              {children}
              <Toaster position="bottom-right" closeButton richColors />
            </LayoutWrapper>
          </PrimaryLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
