import { AuthProvider } from '@/app/contexts/AuthContext';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import PrimaryLayout from './components/layouts/primary/PrimaryLayout';
import SidebarLayout from './components/layouts/sidebar/SidebarLayout';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Lumea',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PrimaryLayout>
            <div className="flex ">
              <SidebarLayout />
              <div className="w-full overflow-x-auto">
                <div className="sm:h-[calc(99vh-60px)] overflow-auto">
                  <div className="w-full px-10 flex-col justify-start items-start overflow-auto h-[calc(100vh - 120px)] overflow-y-auto relative">
                    <div className="w-full mt-[30px] md:max-w-6xl">
                      {children}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </PrimaryLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
