import { AuthProvider } from '@/app/contexts/AuthContext';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import LayoutWrapper from './components/layouts/LayoutWrapper';
import PrimaryLayout from './components/layouts/primary/PrimaryLayout';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Lumea',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PrimaryLayout>
            <LayoutWrapper>{children}</LayoutWrapper>
          </PrimaryLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
